# -*- coding: utf-8 -*-
"""Копия блокнота "Homework11.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N2vfNaHA9ykKcBonSLVJTPrIkk-p6CNx
"""

# f(x) = -12x^4*sin(cos(x)) - 18x^3+5x^2 + 10x - 30
# 1. Определить корни
# 2. Найти интервалы, на которых функция возрастает
# 3. Найти интервалы, на которых функция убывает
# 4. Построить график
# 5. Вычислить вершину
# 6. Определить промежутки, на котором f > 0
# 7. Определить промежутки, на котором f < 0
#
# На основании графика, учитывая, что промежуток в задании не определен, корней бесконечное количество, интервалов возрастания и убывания также бесконечное количество, как и вершин.
# График построен дважды: с помощью библиотеки sympy и с помощью библиотеки matplotlib.

import sympy

from sympy.plotting import plot
from sympy import symbols

x = symbols('x')

plot((-12)*sympy.sin(sympy.cos(x))*x**4 - 18 * x**3 + 5 * x**2 + 10 * x - 30, (x, -200, 200))

import matplotlib.pyplot as plt
import numpy as np

x_mass = []
y_mass = []
massive = []
x = -200
while x < 200:
    y = -12 * x**4 * np.sin(np.cos(x)) - 18*x**3 + 5*x**2 + 10*x - 30
    y_mass.append(y)
    x_mass.append(x)
    x += 0.1

plt.grid()
plt.plot(x_mass, y_mass)
plt.show()